### ISSUE TITLE
ng-serve webpack: Failed to compile.

### ISSUE THREAD

**Issue by nickelas** [YagoLopez/ng-dashboard#1]
Looks interesting but I am getting the error below when doing ng-serve

```
ERROR in Could not resolve "C:/Users/UsuarioAurora/Documents/WebstormProjects/ng-dashboard/src/app/pages/about/pagAboutMod" from "/home/nikke/slask/ng2/ng-dashboard/src/app/ngDashboardAppMod.ts".
webpack: Failed to compile.
```

**Comment by YagoLopez** [comment]
In https://github.com/YagoLopez/ng-dashboard/blob/master/src/app/ngDashboardAppMod.ts try to adapt `basePath` to your environment.

May be it is `/home/nikke/slask/ng2/ng-dashboard/src/app/pages` or something similar. This is due to webpack needs absolute paths pointing to angular modules that are lazy-loaded. Tell me if that works.

**Comment by YagoLopez** [comment]
To be more precise, the line you have to change is 25:
https://github.com/YagoLopez/ng-dashboard/blob/master/src/app/ngDashboardAppMod.ts#L25
